library(ggplot2)
postscript("test.cqs.ps", width=2000, height=2000)
df <- as.data.frame(read.table("test_cum_quals.tbl",header=TRUE))
ggplot(df, aes (x = xlabel, y=ylabel,color =label,group =label))+ geom_point()+geom_line() + theme(axis.text.x = element_text(size=4,angle=90),plot.background = element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),panel.background = element_blank())+ ggtitle("Cumulative proportion of qualities
for test")+xlab("Quality Score")+ylab("Cumulative Proportion") + labs(color = "sample")
postscript("test.ntbps.ps", width=2000, height=2000)
df2 <- as.data.frame(read.table("test_nucleotides_by_position.tbl",header=TRUE))
ggplot(df2, aes (x = position, y=value ,fill = nucleotide))+geom_bar(stat="identity",linetype="blank")+theme(axis.text.x = element_text(size=4,angle=90),plot.background = element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),panel.background = element_blank()) + ggtitle("Nucleotide Distribution for test")  +xlab("Position")+ylab("Proportion")+labs(fill = "Nucleotide Class")
postscript("test.qdbs.ps", width=2000, height=2000)
df3 <- as.data.frame(read.table("test_quality_distribution.tbl",header=TRUE))
ggplot(df3, aes(x= factor(xlabel),y=ylabel,fill=label, weight = y_weight)) + geom_violin(scale="count",position="identity",linetype="blank") +theme(axis.text.x = element_text(size=4,angle=90),plot.background= element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),panel.background = element_blank())+ ggtitle("Quality Score Distributions by Position")+ xlab("Position") + ylab("Quality Scores") + labs("test")
postscript("test.prf.ps", width=2000, height=2000)
df4 <- as.data.frame(read.table("test_passing_reads.tbl",header=TRUE))
ggplot(df4, aes(x = xlabel, y = ylabel , fill = value)) + geom_tile(aes(fill = value))  + scale_fill_gradient(low="steelblue", high="white")+theme(axis.text.x = element_text(size=4,angle=90),plot.background = element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),panel.background = element_blank()) + ggtitle("Passing reads for test")   + ylab("Minimum Quality Score")+xlab("Number of bases >= Minimum Quality") +labs(fill = "Proportion of Reads")
postscript("test.novelty.ps", width=2000, height=2000)
df5 <- as.data.frame(read.table("test_novelty.tbl",header=TRUE))
ggplot(df5, aes(x=novelty,y=count))+geom_histogram(stat="identity")+ggtitle("Uniqueness of reads for test")+ylab ("Number of reads in category")+xlab("Uniqueness score")
